tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "git"
brew "imagemagick"
brew "jq"
brew "mas"
brew "postgresql", restart_service: true
brew "rbenv"
brew "wget"
brew "yarn"
brew "heroku/brew/heroku"
cask "1password"
cask "atom"
cask "firefox"
cask "google-chrome"
mas "Things3", id: 904280696
